export const orderData = {
  orderId: "32457ABC",
  supplierName: "East Cost Fruits & Vegetables",
  shippingdate: "Thu, Feb 11",
  total: "10000",
  department: "300-44-33",
  category: "Food",
  status: "Awaiting for approval",
  productsList: [
    {
      productName: "Chicken Meat",
      brand: "Sugana",
      total: "1000",
      quantity: 2,
      status: "shipped",
      price: "500",
    },
    {
      productName: "Chicken Meat",
      brand: "Sugana",
      total: "1000",
      quantity: 2,
      status: "shipped",
      price: "500",
    },
    {
      productName: "Chicken Meat",
      brand: "Sugana",
      total: "1000",
      quantity: 2,
      status: "shipped",
      price: "500",
    },
    {
      productName: "Chicken Meat",
      brand: "Sugana",
      total: "1000",
      quantity: 2,
      status: "shipped",
      price: "500",
    },
    {
      productName: "Chicken Meat",
      brand: "Sugana",
      total: "1000",
      quantity: 2,
      status: "shipped",
      price: "500",
    },
  ],
};
